### PR TITLE
BLM statement

### PR DESCRIPTION
**Pull request by rachelkelly**

### CODE REVIEW

**Comment by altsalt** [comment]
I just unpublished this as I've been grading finals all week and have not yet reviewed it. The markdown was not displaying as intended and there are a few open questions I have. Thank you for the enthusiasm and drafting efforts, I do hope to get this out today but really need to have eyes on it first.

**Comment by rachelkelly** [comment]
Hi Salt, we agreed on Friday for pub date, there were four calls to review it, including two after I wrote an initial draft, and it was drafted and reviewed by three staff members.  That is why we published it.  Please let me know when you have done your review so we can publish this as soon as possible.

**Comment by altsalt** [comment]
Will do

**Comment by altsalt** [comment]
It's odd, I can't request @lucywyman as a reviewer on the new PR. That being said, it is up. Thank you for your patience.

**Comment by altsalt** [comment]
I do not feel confident enough with my git-foo (especially at this level of sleep deprivation) to do what I'd like to right now. Instead I'll describe it, and if no one has addressed it by the time I get back on tomorrow, I'll give it a shot.

1) rebase to before this PR was merged
2) add new text from #182 to commit, not necessarily actually merging that commit with a terrible message that wasn't made in a branch...
3) have revisions reviewed and accepted/modified
4) have PR merged again

Going to ping @AndrewKvalheim but I think this is all fairly doable, albeit not really kosher.

Anyway, going to try to address the sleep dep. Will check back tomorrow. Thanks!

**Comment by AndrewKvalheim** [comment]
It's probably best to just continue the review in the next PR:

- BLM statement (continued) #182

**Pull request merged**
