### PR TITLE
Add 2019 Videos Announcement

### PR DESCRIPTION
**Pull request by nhandler**
Add post linking to all available video recordings from 2019.

### CODE REVIEW

**Comment by altsalt** [comment]
Looks great, but we should have a note about some of the recordings not coming out. Here was my message to the speakers, feel free to re-use any of it that is helpful. Thanks much!

> I wanted to send this email to inform you that your talk was one of the ones that didn't turn out.
> 
> We aren't sure where the hiccup was and if we find a stash of video files, then we'll let you know.
> 
> In future years, we will strive to do better with tech support in every room.
> 
> If you made your own recording and would like us to upload it along with the rest, let us know!

**Comment by nhandler** [comment]
Thanks for the feedback. I've added a brief note based on your message. Let me know if that lines up with what you were envisioning.

**Comment by altsalt** [comment]
Yeap, LGTM!

**Comment by nhandler** [comment]
This is not my area of expertise, but I'll adjust the date to be this coming Tuesday (March 17). That puts it a week after the keynote post. This feels like a reasonable length of time that lets the keynote post have time to stand on its own, while also not waiting too long to share this new post.

**Pull request merged**
