### PR TITLE
BLM statement (continued)

### PR DESCRIPTION
**Pull request by altsalt**
Reviewed and revised.

### CODE REVIEW

**Comment by altsalt** [comment]
I now realize that I may not have done this in the cleanest sense, it should really be rebased off of the initial PR from @rachelkelly Alas, I'm out of time right now and wanted to get this up. Feel free to clean up or ping me on IRC if there is something I can do. Thanks!

**Comment by AndrewKvalheim** [comment]
A word diff to work around isaacs/github#832:

git diff --word-diff --word-diff-regex='\w+|.' upstream/master upstream/pull/182

**Comment by AndrewKvalheim** [comment]
> I am not extremely thrilled about my PR being copypasted under another's name.

Just to clarify this point—nothing is copied here. The post in your PR was published, intact and with proper attribution. After that, Salt changed [only the status][unpublish] to draft, and then proposed changes to the text here.

[unpublish]: https://github.com/SeaGL/seagl.github.io/commit/61d81eb0702728ca2fed9632f62463f309adb07d?short_path=738e8cb#diff-738e8cbff3b3c79d1a39b43f7799f150

**Comment by altsalt** [comment]
I wanted to sleep on this before replying to check myself. That being said, I still think it rather pertinent to add my thoughts.

> I do not find these changes substantive enough to warrant pulling the post. Also much of this is phrasing, which does not change the meaning of what was written.

While they may not be substantive, _they are my edits_. Changing the publication status of the post had nothing to do with whether or not there was a ton to add. It was based on the appearance of it not having being reviewed by more people than the framers before it went out.

> This had been posted because the option to edit was up for five days and three staff members had written and reviewed it and collaborated on it. Further, I requested feedback four times before posting it. I would urge you to post it the way that I'd originally had the post up as, because we agreed on a publish date, and there were four reminders to contribute to the draft.

For better or worse, it was decided that I would coordinate the different components of organizing SeaGL this year. Along that vein, I have the expectation that a statement as important as this would not be published without review. Whether that review came from myself, I am slightly less concerned with. However, I would expect the review to come from someone who was not involved with the initial drafting process. In this case, it felt like there was no cross-organization check of a statement that was supposed to come from all of us.

Given that I am in this coordination position, I would have readily done, or arranged for someone else do, this review if a direct message had been sent via Signal, IRC, email, or even the GitHub PR. Everyone involved knows that I have been spending a significant chunk of time and attention on the current events and end of the quarter, but that is a task that I would have made space for. This seems like a clear oversight, and when it went up without having any eyes on it, or a space to add text, I reacted swiftly.

While this may sound a bit greedy, I want to make it clear that the source of my frustration was not about MY ability to add and review.

> Further further, I am not extremely thrilled about my PR being copypasted under another's name. 

As @AndrewKvalheim points out above, this is not the case. In fact, my initial request was to re-write history so that my edits would end up inside your PR, thus keeping it entirely over there. That being said, I do see sense in this method.

> If you do not post it as it was, that's fine, then post it like this. Please post something soon; I want our community to know that we support them.

The only reason that I have withheld merging my edits is that I wanted them to be reviewed by someone else. I would like to point out that the edits and request for review was available before EOD Friday and that there is no substantive difference between this statement having gone up Friday instead of Saturday, or for that matter today, Monday.

Thank you @rachelkelly and @lucywyman for all of your work drafting the vast majority of this statement and now having gone over my additions. I will now merge and make the statement is public.

**Comment by kormoc** [comment]
I am disappointed in how this was handled. Even though I was late to the call on Monday last week, I was aware of the review/publish deadlines. 

Please, correct me if I'm wrong, but it appears that the action was taken without any attempt at communicating with @rachelkelly before hand or getting any consensus for the actions with other members of the staff. I understand that you're acting as the ring leader this year, however I don't believe that it's acceptable to unilaterally modify another committee's work without any communication and agreement beforehand, with the exception of something particularly egregious, which this does not meet. Posts can be updated for clarity or deleted and reposted to trigger new RSS feeds.

There was ample time to object to the stated process last week, and there was ample time to request an extension or review the post. I firmly believe in the staff members we have and I feel this was disrespectful of their time, energy, and the collaborative nature of the organization. 

Just my $0.02.

**Comment by altsalt** [comment]
Thank you for your feedback on this @kormoc and for generally jumping in lately!

As mentioned above, I reacted swiftly, however, I did check-in with the only person who seemed active on IRC at the time so as to verify that I wasn't being completely rash, before pulling the post.

There have been a couple of instances when I've wanted to check-in with someone and not found them available through any, known to me, avenue but email, which can be rather slow. Perhaps there is a communication channel tension that is surfacing here and can be addressed at the next meeting?

All that said, I do think that you are correct that I could have handled this better. In the end, what @rachelkelly said about the nature of the post being more important than the actual words is well reasoned. I'm sorry for being hasty and really do appreciate everyone's time, effort, and energy, and do not mean to disrespect any of that.

**Pull request merged**
