### PR TITLE
self-compilable snacks for social events

### PR DESCRIPTION
**Pull request by lufthans**

### CODE REVIEW

**Comment by lufthans** [comment]
out of the box ( at trebuchet velocity ) social event recipes blog post proposal

The link to the recipes repo is from UX committee, the ideas and wording of the post are my fault.

**Comment by altsalt** [comment]
I will modify this blog post shortly to include the theme and more attend details as a day-before post.

**Comment by AndrewKvalheim** [comment]
Can you add a link here when publishing?

https://github.com/SeaGL/seagl.github.io/blob/7ab231a678ed6ce0adb01cbe40837f76eea6c317/_includes/jumbotron.html#L5

**Comment by altsalt** [comment]
superseeded by #371

**Pull request closed without merging**
