### PR TITLE
Add Kathy Giori Keynote Interview

### PR DESCRIPTION
**Pull request by nhandler**

### CODE REVIEW

**Comment by funnelfiasco** [comment]
@nhandler did you mean to merge this without reviews?

**Comment by nhandler** [comment]
> @nhandler did you mean to merge this without reviews?

In this particular case, yes. I had discussed this post with @rachelkelly on Friday, and we opted to push the interview as soon as it could be converted over to markdown and then deal with any minor issues that might have crept in as follow-up edits. The PR was more designed as an FYI that this was going out (as most people probably don't have notifications turned on for new commits).

Was there an issue with the post content?

**Comment by funnelfiasco** [comment]
Nope, it looked good to me. Just checking. :-)

**Comment by nhandler** [comment]
> Nope, it looked good to me. Just checking. :-)

Appreciate it, thanks :)

**Pull request merged**
